version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/openjdk:8-jdk

jobs:
  test:
    <<: *defaults

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-

      - run: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run: ./gradlew build

      - store_test_results:
          path: api/build/test-results

      - store_test_results:
          path: worker/build/test-results

      - store_test_results:
          path: common/build/test-results

      - store_artifacts:
          path: api/build/reports
          destination: reports-api

      - store_artifacts:
          path: worker/build/reports
          destination: reports-worker

      - store_artifacts:
          path: common/build/reports
          destination: reports-common

      - persist_to_workspace:
          root: .
          paths:
            - api/build
            - worker/build

  publish-api:
    <<: *defaults

    docker:
      - image: circleci/python:2.7-jessie

    steps:
      - checkout

      - attach_workspace:
          at: .

      - setup_remote_docker

      - run:
          name: Checkout Docker publish script
          command: curl https://gist.githubusercontent.com/superafroman/ca7422b3c925dfeba5854edcc1713d89/raw/77febaa0954dfa8ebc6598b1366b7f1f8e38d610/docker-publish.sh -O && chmod +x docker-publish.sh

      - run:
          name: Install awscli
          command: sudo pip install awscli

      - run:
          name: Publish docker image
          command: cd api && ../docker-publish.sh eu-west-2 523508197323.dkr.ecr.eu-west-2.amazonaws.com fco casemanagement-api

      - persist_to_workspace:
          root: .
          paths:
            - api/tag.txt

  publish-worker:
    <<: *defaults

    docker:
      - image: circleci/python:2.7-jessie

    steps:
      - checkout

      - attach_workspace:
          at: .

      - setup_remote_docker

      - run:
          name: Checkout Docker publish script
          command: curl https://gist.githubusercontent.com/superafroman/ca7422b3c925dfeba5854edcc1713d89/raw/77febaa0954dfa8ebc6598b1366b7f1f8e38d610/docker-publish.sh -O && chmod +x docker-publish.sh

      - run:
          name: Install awscli
          command: sudo pip install awscli

      - run:
          name: Publish docker image
          command: cd worker && ../docker-publish.sh eu-west-2 523508197323.dkr.ecr.eu-west-2.amazonaws.com fco casemanagement-worker

      - persist_to_workspace:
          root: .
          paths:
            - worker/tag.txt

  deploy:
    <<: *defaults

    docker:
      - image: circleci/python:2.7-jessie

    steps:
      - checkout

      - attach_workspace:
          at: .

      - run:
          name: Deploy
          command: |
            TAG=`cat api/tag.txt`
            echo "Someday I'll deploy version ${TAG}"

workflows:
  "Test, publish and deploy":
    jobs:
      - test
      - publish-api:
          requires:
            - test
      - publish-worker:
          requires:
            - test
      - deploy:
          requires:
            - publish-api
            - publish-worker
          filters:
            branches:
              only:
                - master
