
spring:
  jackson:
    default-property-inclusion: non_absent
    serialization:
      write_dates_as_timestamps: false
  resources:
    add-mappings: false

server:
  port: 9000
  servlet:
    context-path: /v1

springdoc:
  api-docs:
    path: /api-docs

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: ${ROOT_LOGGING_LEVEL:DEBUG}
    com.amazonaws: DEBUG
    org.apache.http: INFO
    org.springframework: INFO

message-queue:
  endpoint: ${MESSAGE_QUEUE_ENDPOINT:http://localhost:9324}
  queue-url: ${MESSAGE_QUEUE_URL:http://localhost:9324/queues/default}
  internal-queue-prefix: ${INTERNAL_QUEUE_PREFIX:casemgmt-requester}
  request-timeout: 30000

---

spring:
  profiles: production
