
spring:
  jackson:
    default-property-inclusion: non_absent
    serialization:
      write_dates_as_timestamps: false
  resources:
    add-mappings: false

server:
  port: 9000
  servlet:
    context-path: /v1

springdoc:
  api-docs:
    path: /api-docs

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: ${ROOT_LOGGING_LEVEL:DEBUG}
    com.amazonaws: INFO
    org.apache.http: INFO
    org.springframework: INFO

message-queue:
  endpoint: ${MESSAGE_QUEUE_ENDPOINT:https://sqs.eu-west-1.amazonaws.com}
  queue-url: ${MESSAGE_QUEUE_URL:https://sqs.eu-west-1.amazonaws.com/545108028694/fco-forms-casemanagement-queue.fifo}
  internal-queue-prefix: ${INTERNAL_QUEUE_PREFIX:casemanagment-requester}
  request-timeout: 30000

---

spring:
  profiles: production
